apiVersion: v1
kind: Secret
metadata:
  name: comforthotel-secrets
  namespace: comforthotel
type: Opaque
stringData:
  DB_PASSWORD: change_me_db_password
  SESSION_SECRET: change_me_session_secret
  ADMIN_PASSWORD: change_me_admin_password
  MANAGER_PASSWORD: change_me_manager_password
  USER_PASSWORD: ""
